#!/bin/bash

# this function makes it easier to ensure that we are using the same remote backend for our state file, I got tired of typing it every time I re-launched the cloud shell. 

function tf-init {
 terraform init -backend-config="storage_account_name=xxxxxx" -backend-config="container_name=tfstate" -backend-config="access_key=xxxxxxxxxxxxxxx" -backend-config="key=codelab.microsoft.tfstate" 
}


#this function is just a short hand for ensuring our plan is written out to a file
function tf-plan {
 terraform plan -out out.plan
}

#short hand for applying out.plan file
function tf-apply {
 terraform apply out.plan
}

#quick apply to create AKS cluster without modifying the main.tf
function tf-aks-plan {
 terraform plan -out out.plan --target module.aks-cluster
}

#quick apply to create consul 
function tf-consul-plan {
 terraform plan -out out.plan --target module.consul-helm
}

#used for destroying jenkins 
function tf-destroy-jenkins {
 terraform destroy --target module.jenkins-helm
}

#function used for setting the kubeconfig env_var. this is necessary whenever you reconnect to the cloud shell and lose your session
function kube-set {
 export KUBECONFIG=./azurek8s
}

#used to output something from our terraform outputs directly to a local file
function kube-output {
 echo "$(terraform output --module="aks-cluster" kube_config ) " > azurek8s
}

#used for displaying the kube_config file in the console
function kube-show {
terraform output --module="aks-cluster" kube_config
}

#wrapper function
function kube-init {
 kube-output
 kube-set
}

